CREATE TYPE "NotificationCategory" AS ENUM('SECURITY','TRANSACTION','COMPLIANCE','SERVICE','REMINDER','INFORMATION','PROMOTION','ADMINISTRATION');
CREATE TYPE "NotificationPriority" AS ENUM('LOW','NORMAL','HIGH','CRITICAL');
CREATE TYPE "NotificationStatus" AS ENUM('CREATED','READ','EXPIRED','CANCELLED');
CREATE TYPE "NotificationSensitivity" AS ENUM('PUBLIC','PRIVATE','SENSITIVE');
CREATE TABLE "notifications"("id" UUID NOT NULL,"public_reference" VARCHAR(50) NOT NULL,"recipient_user_id" UUID NOT NULL,"type" VARCHAR(150) NOT NULL,"category" "NotificationCategory" NOT NULL,"priority" "NotificationPriority" NOT NULL DEFAULT 'NORMAL',"status" "NotificationStatus" NOT NULL DEFAULT 'CREATED',"sensitivity" "NotificationSensitivity" NOT NULL DEFAULT 'PRIVATE',"title" VARCHAR(150) NOT NULL,"body" VARCHAR(500) NOT NULL,"locale" VARCHAR(15) NOT NULL,"country_code" CHAR(2) NOT NULL,"environment" VARCHAR(30) NOT NULL,"idempotency_key" VARCHAR(150) NOT NULL,"request_hash" CHAR(64) NOT NULL,"source" VARCHAR(100) NOT NULL,"business_reference" VARCHAR(100),"correlation_id" VARCHAR(100),"metadata" JSONB,"expires_at" TIMESTAMPTZ(6),"read_at" TIMESTAMPTZ(6),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "notifications_pkey" PRIMARY KEY("id"));
CREATE TABLE "notification_audit"("id" UUID NOT NULL,"notification_id" UUID NOT NULL,"actor_user_id" UUID,"action" VARCHAR(150) NOT NULL,"details" JSONB,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "notification_audit_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "notifications_public_reference_key" ON "notifications"("public_reference");CREATE UNIQUE INDEX "notifications_environment_idempotency_key_key" ON "notifications"("environment","idempotency_key");CREATE INDEX "notifications_recipient_user_id_status_created_at_idx" ON "notifications"("recipient_user_id","status","created_at");CREATE INDEX "notifications_category_priority_created_at_idx" ON "notifications"("category","priority","created_at");CREATE INDEX "notifications_correlation_id_idx" ON "notifications"("correlation_id");CREATE INDEX "notification_audit_notification_id_created_at_idx" ON "notification_audit"("notification_id","created_at");CREATE INDEX "notification_audit_actor_user_id_created_at_idx" ON "notification_audit"("actor_user_id","created_at");
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_recipient_user_id_fkey" FOREIGN KEY("recipient_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "notification_audit" ADD CONSTRAINT "notification_audit_notification_id_fkey" FOREIGN KEY("notification_id") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "notification_audit" ADD CONSTRAINT "notification_audit_actor_user_id_fkey" FOREIGN KEY("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- PrismaUnsupportedStart
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_read_status_consistent" CHECK(("status"='READ' AND "read_at" IS NOT NULL) OR ("status"<>'READ' AND "read_at" IS NULL));
CREATE TRIGGER notification_audit_immutable BEFORE UPDATE OR DELETE ON "notification_audit" FOR EACH ROW EXECUTE FUNCTION protect_wallet_audit();
-- PrismaUnsupportedEnd
INSERT INTO "permissions"("id","code","description","critical")VALUES('00000000-0000-4000-8000-000000000931','notification.self.read','Consulter ses notifications',false),('00000000-0000-4000-8000-000000000932','notification.self.update','Marquer ses notifications comme lues',false),('00000000-0000-4000-8000-000000000933','notification.read','Consulter les notifications',true),('00000000-0000-4000-8000-000000000934','notification.send','Créer une notification',true),('00000000-0000-4000-8000-000000000935','notification.audit.read','Consulter l’audit des notifications',true);
