CREATE TYPE "KycLevel" AS ENUM ('LEVEL_0','LEVEL_1','LEVEL_2','LEVEL_3');
CREATE TYPE "KycStatus" AS ENUM ('NOT_STARTED','IN_PROGRESS','SUBMITTED','AUTOMATIC_REVIEW','MANUAL_REVIEW','ADDITIONAL_INFORMATION_REQUIRED','APPROVED','REJECTED','EXPIRED','SUSPENDED');
CREATE TABLE "kyc_profiles" ("id" UUID NOT NULL,"user_id" UUID NOT NULL,"country_code" CHAR(2) NOT NULL,"level" "KycLevel" NOT NULL DEFAULT 'LEVEL_0',"requested_level" "KycLevel" NOT NULL DEFAULT 'LEVEL_1',"status" "KycStatus" NOT NULL DEFAULT 'NOT_STARTED',"provider_reference" VARCHAR(150),"submitted_at" TIMESTAMPTZ(6),"reviewed_at" TIMESTAMPTZ(6),"expires_at" TIMESTAMPTZ(6),"decision_reason" VARCHAR(500),"version" INTEGER NOT NULL DEFAULT 1,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "kyc_profiles_pkey" PRIMARY KEY("id"));
CREATE TABLE "kyc_audit" ("id" UUID NOT NULL,"profile_id" UUID NOT NULL,"actor_user_id" UUID,"action" VARCHAR(150) NOT NULL,"reason" VARCHAR(500),"details" JSONB,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "kyc_audit_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "kyc_profiles_user_id_key" ON "kyc_profiles"("user_id");CREATE INDEX "kyc_profiles_status_submitted_at_idx" ON "kyc_profiles"("status","submitted_at");CREATE INDEX "kyc_audit_profile_id_created_at_idx" ON "kyc_audit"("profile_id","created_at");CREATE INDEX "kyc_audit_actor_user_id_created_at_idx" ON "kyc_audit"("actor_user_id","created_at");
ALTER TABLE "kyc_profiles" ADD CONSTRAINT "kyc_profiles_user_id_fkey" FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "kyc_audit" ADD CONSTRAINT "kyc_audit_profile_id_fkey" FOREIGN KEY("profile_id") REFERENCES "kyc_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "kyc_audit" ADD CONSTRAINT "kyc_audit_actor_user_id_fkey" FOREIGN KEY("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- PrismaUnsupportedStart
CREATE TRIGGER kyc_audit_immutable BEFORE UPDATE OR DELETE ON "kyc_audit" FOR EACH ROW EXECUTE FUNCTION protect_wallet_audit();
-- PrismaUnsupportedEnd
INSERT INTO "permissions"("id","code","description","critical") VALUES ('00000000-0000-4000-8000-000000000901','kyc.self.write','Démarrer et soumettre son KYC',true),('00000000-0000-4000-8000-000000000902','kyc.self.read','Consulter son KYC',true),('00000000-0000-4000-8000-000000000903','kyc.review','Décider une revue KYC',true),('00000000-0000-4000-8000-000000000904','kyc.read','Consulter les dossiers KYC',true),('00000000-0000-4000-8000-000000000905','kyc.audit.read','Consulter audit KYC',true);
