CREATE TYPE "TransferType" AS ENUM('MANSA_TO_MANSA');
CREATE TYPE "TransferStatus" AS ENUM('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED','REVERSED');
CREATE TABLE "transfers"("id" UUID NOT NULL,"public_reference" VARCHAR(50) NOT NULL,"type" "TransferType" NOT NULL DEFAULT 'MANSA_TO_MANSA',"status" "TransferStatus" NOT NULL DEFAULT 'PENDING',"payment_id" UUID,"sender_wallet_id" UUID NOT NULL,"recipient_user_id" UUID NOT NULL,"recipient_handle" VARCHAR(30) NOT NULL,"amount" BIGINT NOT NULL,"currency_code" CHAR(3) NOT NULL,"country_code" CHAR(2) NOT NULL,"environment" VARCHAR(30) NOT NULL,"idempotency_key" VARCHAR(150) NOT NULL,"request_hash" CHAR(64) NOT NULL,"message" VARCHAR(280),"initiated_by_user_id" UUID NOT NULL,"completed_at" TIMESTAMPTZ(6),"failure_code" VARCHAR(100),"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL,CONSTRAINT "transfers_pkey" PRIMARY KEY("id"));
CREATE TABLE "transfer_audit"("id" UUID NOT NULL,"transfer_id" UUID NOT NULL,"actor_user_id" UUID,"action" VARCHAR(150) NOT NULL,"details" JSONB,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "transfer_audit_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "transfers_public_reference_key" ON "transfers"("public_reference");CREATE UNIQUE INDEX "transfers_payment_id_key" ON "transfers"("payment_id");CREATE UNIQUE INDEX "transfers_environment_idempotency_key_key" ON "transfers"("environment","idempotency_key");CREATE INDEX "transfers_initiated_by_user_id_created_at_idx" ON "transfers"("initiated_by_user_id","created_at");CREATE INDEX "transfers_recipient_user_id_created_at_idx" ON "transfers"("recipient_user_id","created_at");CREATE INDEX "transfers_status_created_at_idx" ON "transfers"("status","created_at");CREATE INDEX "transfer_audit_transfer_id_created_at_idx" ON "transfer_audit"("transfer_id","created_at");CREATE INDEX "transfer_audit_actor_user_id_created_at_idx" ON "transfer_audit"("actor_user_id","created_at");
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_payment_id_fkey" FOREIGN KEY("payment_id") REFERENCES "payments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "transfers" ADD CONSTRAINT "transfers_sender_wallet_id_fkey" FOREIGN KEY("sender_wallet_id") REFERENCES "wallets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "transfers" ADD CONSTRAINT "transfers_recipient_user_id_fkey" FOREIGN KEY("recipient_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "transfers" ADD CONSTRAINT "transfers_initiated_by_user_id_fkey" FOREIGN KEY("initiated_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "transfer_audit" ADD CONSTRAINT "transfer_audit_transfer_id_fkey" FOREIGN KEY("transfer_id") REFERENCES "transfers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;ALTER TABLE "transfer_audit" ADD CONSTRAINT "transfer_audit_actor_user_id_fkey" FOREIGN KEY("actor_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- PrismaUnsupportedStart
ALTER TABLE "transfers" ADD CONSTRAINT "transfers_amount_positive" CHECK("amount">0);
CREATE TRIGGER transfer_audit_immutable BEFORE UPDATE OR DELETE ON "transfer_audit" FOR EACH ROW EXECUTE FUNCTION protect_wallet_audit();
-- PrismaUnsupportedEnd
INSERT INTO "permissions"("id","code","description","critical")VALUES('00000000-0000-4000-8000-000000000921','transfer.self.create','Créer un transfert Mansa à Mansa',true),('00000000-0000-4000-8000-000000000922','transfer.self.read','Consulter ses transferts',false),('00000000-0000-4000-8000-000000000923','transfer.read','Consulter les transferts',true),('00000000-0000-4000-8000-000000000924','transfer.audit.read','Consulter l’audit des transferts',true);
